### ISSUE TITLE
Question: Overview over the Connectivity between the Ephemeral Pods

### ISSUE THREAD

**Issue by kindlich** [carbynestack/carbynestack#21]
Hey there,

I have some questions about the way that the Ephemeral pods are communicating with each other, especially when it comes to scaling up.

So first I would like to check if my understanding of the different components is correct (only looking at the networking aspects here)?
- `networks.mpc.bosch.com` K8S CRD: Describes how **Inbound** traffic should be routed to the MPC pod
  Will configure Istio to create the routes from the outward port (30000+) to the Pod in question (e.g. ephemeral-generic-00001-..., Port 5000 on the first VPC)
- `network/Proxy` component in Ephemeral-Ephemeral: Used to forward the **outgoing** requests from the MPC Pod to the other VPC parties.
- `Ephemeral-Discovery`: Helps the different Ephemeral-Ephemeral "computing" pods to find each other for a calculation
  Responsible for exchanging information about the IP addresses and Public ports of the participants

So now some questions: 
1) So, if we scaled this up to a 3rd VPC (let's name it Boomer for now), would the connectivity look like this?
![Ephemeral_Network_Connectivity](https://user-images.githubusercontent.com/10351787/144290876-6d13fedf-1400-473e-94e9-2703983b932d.png)

2) Is there already a plan to have more than 5 instances of `network.mpc.bosch.com` at the same time (the Istio Ingress Gateway only has ports 30000~30004 open in the istio-ingressgateway that the example deploys)

3) What is the reasoning behind the proxy?   
  Since you already use call `Player-Online.x` with an  `--ip-file-name /mp-spdz/ip-file`, why not fill in the other party's addresses/ports in there?
  Doesn't the Proxy only add an unnecessary (possibly faulty) component to the setup (and from the code it would need some revising  anyways since the code can only create one proxy forwarding atm).

BR,
kindlich

**Comment by strieflin** [comment]
Hi @kindlich,

**DISCLAIMER**: _I am not the original author of the Ephemeral code base, so my understanding might be incomplete or even wrong._

Your understanding of the Ephemeral subsystem seems to be correct at a high level. In my attempt to wrap my head around the implementation, I created the following diagram that might help you as well in your attempt to understand the purpose of the individual components:

![ephemeral](https://user-images.githubusercontent.com/7703809/144382185-573b198b-4ed6-435e-88cc-0c5607e6327c.png)

Regarding your questions:

1. If I remember correctly, MP-SPDZ implements a scheme, where player `i` connects to all players `[i,n]` (or the other way round) resulting in a fully connected mesh. Note that CS only supports 2 VCPs as of today.
2. There is no rationale behind the limitation to 5 ports. We simply didn't want to pollute the resource manifest with too many port declarations. Technically, there is no limitation (except number of available ports).
3. The proxy is used for doing a connectivity check to avoid MP-SPDZ engines to abort due to responses from the other parties that violate the protocol, e.g., the ingress complaining about unavailable downstream services.

@vvraskin (original author): Anything that you want to add to the discussion?

**Off-topic** @kindlich: Can you elaborate a little bit about your motivation of looking into Carbyne Stack? What is the use case? What is your affiliation? If that information is sensitive you can also send me a PM.

**Comment by kindlich** [comment]
Yep, can be closed from my side, thanks.
